### PR TITLE
add redis container and support database deletion

### PR DESCRIPTION
**Pull request by travistran1989**

### CODE REVIEW

**Review by Code-Egg — COMMENTED** [review]
For the delete database option, it seems like the domain is not required, can we remove line 185, and update the help message according to it?

**Comment by travistran1989** [comment]
Sure. Thank you!

**Comment by Code-Egg** [comment]
I just did a quick test, and it seems that inputting the `redis` to the field would make it work, no port open is needed. 
redis

**Comment by travistran1989** [comment]
Yes. Because it uses the default port of redis service. Connect to redis
container via docker's managed network is more secure than open ports
because docker adds them to firewall automatically.

**Pull request merged**
